"""add sync state to powens_credentials

Revision ID: cb1c9b264dca
Revises: 49989595e450
Create Date: 2026-05-25 16:34:23.638779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1c9b264dca'
down_revision: Union[str, Sequence[str], None] = '49989595e450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('powens_credentials', sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('powens_credentials', sa.Column('last_webhook_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('powens_credentials', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('powens_credentials', sa.Column('last_positions_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('powens_credentials', sa.Column('last_cash_balance', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('powens_credentials', 'last_cash_balance')
    op.drop_column('powens_credentials', 'last_positions_count')
    op.drop_column('powens_credentials', 'last_error')
    op.drop_column('powens_credentials', 'last_webhook_at')
    op.drop_column('powens_credentials', 'last_sync_at')
    # ### end Alembic commands ###
