"""add bank_accounts account_holdings bank_transactions

Revision ID: f3213d0e26ff
Revises: cb1c9b264dca
Create Date: 2026-05-25 19:02:52.669468

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3213d0e26ff"
down_revision: str | Sequence[str] | None = "cb1c9b264dca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_account_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="EUR"),
        sa.Column("balance", sa.Float(), nullable=False, server_default="0"),
        sa.Column("iban", sa.String(length=64), nullable=True),
        sa.Column("institution_name", sa.String(length=255), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "provider", "provider_account_id", name="uq_bank_accounts_user_provider_acc"
        ),
    )
    op.create_index(op.f("ix_bank_accounts_type"), "bank_accounts", ["type"], unique=False)
    op.create_index(op.f("ix_bank_accounts_user_id"), "bank_accounts", ["user_id"], unique=False)
    op.create_table(
        "account_holdings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bank_account_id", sa.UUID(), nullable=False),
        sa.Column("provider_investment_id", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False, server_default="0"),
        sa.Column("unit_price", sa.Float(), nullable=False, server_default="0"),
        sa.Column("current_value", sa.Float(), nullable=False, server_default="0"),
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="EUR"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bank_account_id"], ["bank_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bank_account_id", "provider_investment_id", name="uq_holdings_account_provider_inv"
        ),
    )
    op.create_index(
        op.f("ix_account_holdings_bank_account_id"),
        "account_holdings",
        ["bank_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_holdings_ticker"), "account_holdings", ["ticker"], unique=False
    )
    op.create_index(
        op.f("ix_account_holdings_user_id"), "account_holdings", ["user_id"], unique=False
    )
    op.create_table(
        "bank_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bank_account_id", sa.UUID(), nullable=False),
        sa.Column("provider_transaction_id", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="EUR"),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False, server_default=""),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bank_account_id"], ["bank_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bank_account_id", "provider_transaction_id", name="uq_bank_tx_account_provider_tx"
        ),
    )
    op.create_index(
        op.f("ix_bank_transactions_bank_account_id"),
        "bank_transactions",
        ["bank_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_transactions_category"), "bank_transactions", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_bank_transactions_transaction_date"),
        "bank_transactions",
        ["transaction_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_transactions_user_id"), "bank_transactions", ["user_id"], unique=False
    )
    op.alter_column(
        "powens_credentials",
        "last_positions_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "powens_credentials",
        "last_cash_balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "powens_credentials",
        "last_cash_balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0'::double precision"),
        existing_nullable=False,
    )
    op.alter_column(
        "powens_credentials",
        "last_positions_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_bank_transactions_user_id"), table_name="bank_transactions")
    op.drop_index(op.f("ix_bank_transactions_transaction_date"), table_name="bank_transactions")
    op.drop_index(op.f("ix_bank_transactions_category"), table_name="bank_transactions")
    op.drop_index(op.f("ix_bank_transactions_bank_account_id"), table_name="bank_transactions")
    op.drop_table("bank_transactions")
    op.drop_index(op.f("ix_account_holdings_user_id"), table_name="account_holdings")
    op.drop_index(op.f("ix_account_holdings_ticker"), table_name="account_holdings")
    op.drop_index(op.f("ix_account_holdings_bank_account_id"), table_name="account_holdings")
    op.drop_table("account_holdings")
    op.drop_index(op.f("ix_bank_accounts_user_id"), table_name="bank_accounts")
    op.drop_index(op.f("ix_bank_accounts_type"), table_name="bank_accounts")
    op.drop_table("bank_accounts")
    # ### end Alembic commands ###
